Feature/include allure history (#2)
* update to pull previous artifact history files from circleci
* include random fail step to show history
* adding step to ensure no-fail status for circleci/ga
* update to ignore history failure

diff --git a/.github/workflows/github-actions-ci.yml b/.github/workflows/github-actions-ci.yml
--- a/.github/workflows/github-actions-ci.yml
+++ b/.github/workflows/github-actions-ci.yml
@@ -34,19 +34,30 @@ jobs:
           pip install -r requirements.txt
 
       - name: Run tests with pytest; html extension
+        id: full_run_01
         run: pytest --html=test_result_report.html --self-contained-html
+        continue-on-error: true # ignore the random fail steps
 
       - name: Run tests with pytest; txt extension
+        id: full_run_02
         run: pytest > test_result_default.txt
+        continue-on-error: true # ignore the random fail steps
 
       - name: Run tests with pytest; txt extension
+        id: run_test_01
         run: pytest hello_test.py -k test_capitalize_string_01 > test_result_01.txt
 
       - name: Run tests with pytest; txt extension
+        id: run_test_02
         run: pytest hello_test.py::TestCap::test_capitalize_string_02 > test_result_02.txt
 
       - name: Run tests with pytest; log extension
+        id: run_test_03
         run: pytest -m fruits > test_result_03.log
+
+      - name: Check on failures #sandbox step to ensure at least one test is successful
+        if: steps.run_test_01.outcome != 'success' || steps.run_test_02.outcome != 'success' || steps.run_test_03.outcome != 'success'
+        run: exit 1
 
       - name: Archive test results
         uses: actions/upload-artifact@v2
